version: "3.4"

services:
    node:
        image: node
        container_name: "uischema-org--node"
        restart: unless-stopped
        command: bash -c "cd /var/www/app && node main.js serve"
        ports:
            - "${PORT:-4000}:4000"
        volumes:
            - ./:/var/www
